// Generated by gencpp from file myprocess/myprocess_position.msg
// DO NOT EDIT!


#ifndef MYPROCESS_MESSAGE_MYPROCESS_POSITION_H
#define MYPROCESS_MESSAGE_MYPROCESS_POSITION_H

#include <ros/service_traits.h>


#include <myprocess/myprocess_positionRequest.h>
#include <myprocess/myprocess_positionResponse.h>


namespace myprocess
{

struct myprocess_position
{

typedef myprocess_positionRequest Request;
typedef myprocess_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct myprocess_position
} // namespace myprocess


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myprocess::myprocess_position > {
  static const char* value()
  {
    return "2020962a1bb2cd737e928d23469d8479";
  }

  static const char* value(const ::myprocess::myprocess_position&) { return value(); }
};

template<>
struct DataType< ::myprocess::myprocess_position > {
  static const char* value()
  {
    return "myprocess/myprocess_position";
  }

  static const char* value(const ::myprocess::myprocess_position&) { return value(); }
};


// service_traits::MD5Sum< ::myprocess::myprocess_positionRequest> should match 
// service_traits::MD5Sum< ::myprocess::myprocess_position > 
template<>
struct MD5Sum< ::myprocess::myprocess_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myprocess::myprocess_position >::value();
  }
  static const char* value(const ::myprocess::myprocess_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myprocess::myprocess_positionRequest> should match 
// service_traits::DataType< ::myprocess::myprocess_position > 
template<>
struct DataType< ::myprocess::myprocess_positionRequest>
{
  static const char* value()
  {
    return DataType< ::myprocess::myprocess_position >::value();
  }
  static const char* value(const ::myprocess::myprocess_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myprocess::myprocess_positionResponse> should match 
// service_traits::MD5Sum< ::myprocess::myprocess_position > 
template<>
struct MD5Sum< ::myprocess::myprocess_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myprocess::myprocess_position >::value();
  }
  static const char* value(const ::myprocess::myprocess_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myprocess::myprocess_positionResponse> should match 
// service_traits::DataType< ::myprocess::myprocess_position > 
template<>
struct DataType< ::myprocess::myprocess_positionResponse>
{
  static const char* value()
  {
    return DataType< ::myprocess::myprocess_position >::value();
  }
  static const char* value(const ::myprocess::myprocess_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPROCESS_MESSAGE_MYPROCESS_POSITION_H
