// Generated by gencpp from file myprocess/myprocess_poseResponse.msg
// DO NOT EDIT!


#ifndef MYPROCESS_MESSAGE_MYPROCESS_POSERESPONSE_H
#define MYPROCESS_MESSAGE_MYPROCESS_POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>

namespace myprocess
{
template <class ContainerAllocator>
struct myprocess_poseResponse_
{
  typedef myprocess_poseResponse_<ContainerAllocator> Type;

  myprocess_poseResponse_()
    : result()  {
    }
  myprocess_poseResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::myprocess::myprocess_poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myprocess::myprocess_poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct myprocess_poseResponse_

typedef ::myprocess::myprocess_poseResponse_<std::allocator<void> > myprocess_poseResponse;

typedef boost::shared_ptr< ::myprocess::myprocess_poseResponse > myprocess_poseResponsePtr;
typedef boost::shared_ptr< ::myprocess::myprocess_poseResponse const> myprocess_poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myprocess::myprocess_poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myprocess::myprocess_poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myprocess

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'myprocess': ['/home/li/ROS/myros/src/myprocess/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myprocess::myprocess_poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myprocess::myprocess_poseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myprocess::myprocess_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myprocess::myprocess_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myprocess::myprocess_poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myprocess::myprocess_poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myprocess::myprocess_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8a649bfeb277adfa469bbcaeb9c828b";
  }

  static const char* value(const ::myprocess::myprocess_poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8a649bfeb277adfULL;
  static const uint64_t static_value2 = 0xa469bbcaeb9c828bULL;
};

template<class ContainerAllocator>
struct DataType< ::myprocess::myprocess_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myprocess/myprocess_poseResponse";
  }

  static const char* value(const ::myprocess::myprocess_poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myprocess::myprocess_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64MultiArray result\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
float64[]         data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::myprocess::myprocess_poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myprocess::myprocess_poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myprocess_poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myprocess::myprocess_poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myprocess::myprocess_poseResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYPROCESS_MESSAGE_MYPROCESS_POSERESPONSE_H
