// Generated by gencpp from file myprocess/myprocess_positionRequest.msg
// DO NOT EDIT!


#ifndef MYPROCESS_MESSAGE_MYPROCESS_POSITIONREQUEST_H
#define MYPROCESS_MESSAGE_MYPROCESS_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace myprocess
{
template <class ContainerAllocator>
struct myprocess_positionRequest_
{
  typedef myprocess_positionRequest_<ContainerAllocator> Type;

  myprocess_positionRequest_()
    : name()  {
    }
  myprocess_positionRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::myprocess::myprocess_positionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myprocess::myprocess_positionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct myprocess_positionRequest_

typedef ::myprocess::myprocess_positionRequest_<std::allocator<void> > myprocess_positionRequest;

typedef boost::shared_ptr< ::myprocess::myprocess_positionRequest > myprocess_positionRequestPtr;
typedef boost::shared_ptr< ::myprocess::myprocess_positionRequest const> myprocess_positionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myprocess::myprocess_positionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myprocess::myprocess_positionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myprocess

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'myprocess': ['/home/li/ROS/myros/src/myprocess/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myprocess::myprocess_positionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myprocess::myprocess_positionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myprocess::myprocess_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myprocess::myprocess_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myprocess::myprocess_positionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myprocess::myprocess_positionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myprocess::myprocess_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fce35bd9f5b27a63eb9b0e831759a0b";
  }

  static const char* value(const ::myprocess::myprocess_positionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fce35bd9f5b27a6ULL;
  static const uint64_t static_value2 = 0x3eb9b0e831759a0bULL;
};

template<class ContainerAllocator>
struct DataType< ::myprocess::myprocess_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myprocess/myprocess_positionRequest";
  }

  static const char* value(const ::myprocess::myprocess_positionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myprocess::myprocess_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String name\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::myprocess::myprocess_positionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myprocess::myprocess_positionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myprocess_positionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myprocess::myprocess_positionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myprocess::myprocess_positionRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYPROCESS_MESSAGE_MYPROCESS_POSITIONREQUEST_H
