// Generated by gencpp from file myprocess/myprocess_pose.msg
// DO NOT EDIT!


#ifndef MYPROCESS_MESSAGE_MYPROCESS_POSE_H
#define MYPROCESS_MESSAGE_MYPROCESS_POSE_H

#include <ros/service_traits.h>


#include <myprocess/myprocess_poseRequest.h>
#include <myprocess/myprocess_poseResponse.h>


namespace myprocess
{

struct myprocess_pose
{

typedef myprocess_poseRequest Request;
typedef myprocess_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct myprocess_pose
} // namespace myprocess


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myprocess::myprocess_pose > {
  static const char* value()
  {
    return "a8a649bfeb277adfa469bbcaeb9c828b";
  }

  static const char* value(const ::myprocess::myprocess_pose&) { return value(); }
};

template<>
struct DataType< ::myprocess::myprocess_pose > {
  static const char* value()
  {
    return "myprocess/myprocess_pose";
  }

  static const char* value(const ::myprocess::myprocess_pose&) { return value(); }
};


// service_traits::MD5Sum< ::myprocess::myprocess_poseRequest> should match 
// service_traits::MD5Sum< ::myprocess::myprocess_pose > 
template<>
struct MD5Sum< ::myprocess::myprocess_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myprocess::myprocess_pose >::value();
  }
  static const char* value(const ::myprocess::myprocess_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myprocess::myprocess_poseRequest> should match 
// service_traits::DataType< ::myprocess::myprocess_pose > 
template<>
struct DataType< ::myprocess::myprocess_poseRequest>
{
  static const char* value()
  {
    return DataType< ::myprocess::myprocess_pose >::value();
  }
  static const char* value(const ::myprocess::myprocess_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myprocess::myprocess_poseResponse> should match 
// service_traits::MD5Sum< ::myprocess::myprocess_pose > 
template<>
struct MD5Sum< ::myprocess::myprocess_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myprocess::myprocess_pose >::value();
  }
  static const char* value(const ::myprocess::myprocess_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myprocess::myprocess_poseResponse> should match 
// service_traits::DataType< ::myprocess::myprocess_pose > 
template<>
struct DataType< ::myprocess::myprocess_poseResponse>
{
  static const char* value()
  {
    return DataType< ::myprocess::myprocess_pose >::value();
  }
  static const char* value(const ::myprocess::myprocess_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPROCESS_MESSAGE_MYPROCESS_POSE_H
