(cl:defpackage probot_msgs-srv
  (:use )
  (:export
   "HEARTBEATSRV"
   "<HEARTBEATSRV-REQUEST>"
   "HEARTBEATSRV-REQUEST"
   "<HEARTBEATSRV-RESPONSE>"
   "HEARTBEATSRV-RESPONSE"
   "REFRESHPOINTSSRV"
   "<REFRESHPOINTSSRV-REQUEST>"
   "REFRESHPOINTSSRV-REQUEST"
   "<REFRESHPOINTSSRV-RESPONSE>"
   "REFRESHPOINTSSRV-RESPONSE"
   "SFUCOMMANDCTRL"
   "<SFUCOMMANDCTRL-REQUEST>"
   "SFUCOMMANDCTRL-REQUEST"
   "<SFUCOMMANDCTRL-RESPONSE>"
   "SFUCOMMANDCTRL-RESPONSE"
  ))

