(cl:defpackage probot_msgs-msg
  (:use )
  (:export
   "<CONTROLLERCTRL>"
   "CONTROLLERCTRL"
   "<DEMOCTRL>"
   "DEMOCTRL"
   "<IOSTATUS>"
   "IOSTATUS"
   "<INTERFACERETURNCODE>"
   "INTERFACERETURNCODE"
   "<JOGJOINT>"
   "JOGJOINT"
   "<JOGPOSE>"
   "JOGPOSE"
   "<PREDEFINEDPOINT>"
   "PREDEFINEDPOINT"
   "<PREDEFINEDPOINTLIST>"
   "PREDEFINEDPOINTLIST"
   "<SFUVERSIONNUM>"
   "SFUVERSIONNUM"
   "<SETOUTPUTIO>"
   "SETOUTPUTIO"
  ))

