// Generated by gencpp from file probot_demo/Img_pro.msg
// DO NOT EDIT!


#ifndef PROBOT_DEMO_MESSAGE_IMG_PRO_H
#define PROBOT_DEMO_MESSAGE_IMG_PRO_H

#include <ros/service_traits.h>


#include <probot_demo/Img_proRequest.h>
#include <probot_demo/Img_proResponse.h>


namespace probot_demo
{

struct Img_pro
{

typedef Img_proRequest Request;
typedef Img_proResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Img_pro
} // namespace probot_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::probot_demo::Img_pro > {
  static const char* value()
  {
    return "a0c5e9a3725de657812c1e838d70cecd";
  }

  static const char* value(const ::probot_demo::Img_pro&) { return value(); }
};

template<>
struct DataType< ::probot_demo::Img_pro > {
  static const char* value()
  {
    return "probot_demo/Img_pro";
  }

  static const char* value(const ::probot_demo::Img_pro&) { return value(); }
};


// service_traits::MD5Sum< ::probot_demo::Img_proRequest> should match 
// service_traits::MD5Sum< ::probot_demo::Img_pro > 
template<>
struct MD5Sum< ::probot_demo::Img_proRequest>
{
  static const char* value()
  {
    return MD5Sum< ::probot_demo::Img_pro >::value();
  }
  static const char* value(const ::probot_demo::Img_proRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_demo::Img_proRequest> should match 
// service_traits::DataType< ::probot_demo::Img_pro > 
template<>
struct DataType< ::probot_demo::Img_proRequest>
{
  static const char* value()
  {
    return DataType< ::probot_demo::Img_pro >::value();
  }
  static const char* value(const ::probot_demo::Img_proRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::probot_demo::Img_proResponse> should match 
// service_traits::MD5Sum< ::probot_demo::Img_pro > 
template<>
struct MD5Sum< ::probot_demo::Img_proResponse>
{
  static const char* value()
  {
    return MD5Sum< ::probot_demo::Img_pro >::value();
  }
  static const char* value(const ::probot_demo::Img_proResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_demo::Img_proResponse> should match 
// service_traits::DataType< ::probot_demo::Img_pro > 
template<>
struct DataType< ::probot_demo::Img_proResponse>
{
  static const char* value()
  {
    return DataType< ::probot_demo::Img_pro >::value();
  }
  static const char* value(const ::probot_demo::Img_proResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROBOT_DEMO_MESSAGE_IMG_PRO_H
