// Generated by gencpp from file probot_demo/Img_proRequest.msg
// DO NOT EDIT!


#ifndef PROBOT_DEMO_MESSAGE_IMG_PROREQUEST_H
#define PROBOT_DEMO_MESSAGE_IMG_PROREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace probot_demo
{
template <class ContainerAllocator>
struct Img_proRequest_
{
  typedef Img_proRequest_<ContainerAllocator> Type;

  Img_proRequest_()
    : signal(0)  {
    }
  Img_proRequest_(const ContainerAllocator& _alloc)
    : signal(0)  {
  (void)_alloc;
    }



   typedef uint8_t _signal_type;
  _signal_type signal;





  typedef boost::shared_ptr< ::probot_demo::Img_proRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_demo::Img_proRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Img_proRequest_

typedef ::probot_demo::Img_proRequest_<std::allocator<void> > Img_proRequest;

typedef boost::shared_ptr< ::probot_demo::Img_proRequest > Img_proRequestPtr;
typedef boost::shared_ptr< ::probot_demo::Img_proRequest const> Img_proRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_demo::Img_proRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_demo::Img_proRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace probot_demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::probot_demo::Img_proRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_demo::Img_proRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_demo::Img_proRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_demo::Img_proRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_demo::Img_proRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_demo::Img_proRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_demo::Img_proRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ce8cf9f366ca33ffbb7008845f62def";
  }

  static const char* value(const ::probot_demo::Img_proRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ce8cf9f366ca33fULL;
  static const uint64_t static_value2 = 0xfbb7008845f62defULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_demo::Img_proRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_demo/Img_proRequest";
  }

  static const char* value(const ::probot_demo::Img_proRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_demo::Img_proRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 signal\n\
\n\
";
  }

  static const char* value(const ::probot_demo::Img_proRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_demo::Img_proRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Img_proRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_demo::Img_proRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_demo::Img_proRequest_<ContainerAllocator>& v)
  {
    s << indent << "signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_DEMO_MESSAGE_IMG_PROREQUEST_H
