// Generated by gencpp from file probot_demo/Img_process.msg
// DO NOT EDIT!


#ifndef PROBOT_DEMO_MESSAGE_IMG_PROCESS_H
#define PROBOT_DEMO_MESSAGE_IMG_PROCESS_H

#include <ros/service_traits.h>


#include <probot_demo/Img_processRequest.h>
#include <probot_demo/Img_processResponse.h>


namespace probot_demo
{

struct Img_process
{

typedef Img_processRequest Request;
typedef Img_processResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Img_process
} // namespace probot_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::probot_demo::Img_process > {
  static const char* value()
  {
    return "4c1789e028a38e7750a94a6bd3e727a5";
  }

  static const char* value(const ::probot_demo::Img_process&) { return value(); }
};

template<>
struct DataType< ::probot_demo::Img_process > {
  static const char* value()
  {
    return "probot_demo/Img_process";
  }

  static const char* value(const ::probot_demo::Img_process&) { return value(); }
};


// service_traits::MD5Sum< ::probot_demo::Img_processRequest> should match 
// service_traits::MD5Sum< ::probot_demo::Img_process > 
template<>
struct MD5Sum< ::probot_demo::Img_processRequest>
{
  static const char* value()
  {
    return MD5Sum< ::probot_demo::Img_process >::value();
  }
  static const char* value(const ::probot_demo::Img_processRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_demo::Img_processRequest> should match 
// service_traits::DataType< ::probot_demo::Img_process > 
template<>
struct DataType< ::probot_demo::Img_processRequest>
{
  static const char* value()
  {
    return DataType< ::probot_demo::Img_process >::value();
  }
  static const char* value(const ::probot_demo::Img_processRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::probot_demo::Img_processResponse> should match 
// service_traits::MD5Sum< ::probot_demo::Img_process > 
template<>
struct MD5Sum< ::probot_demo::Img_processResponse>
{
  static const char* value()
  {
    return MD5Sum< ::probot_demo::Img_process >::value();
  }
  static const char* value(const ::probot_demo::Img_processResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_demo::Img_processResponse> should match 
// service_traits::DataType< ::probot_demo::Img_process > 
template<>
struct DataType< ::probot_demo::Img_processResponse>
{
  static const char* value()
  {
    return DataType< ::probot_demo::Img_process >::value();
  }
  static const char* value(const ::probot_demo::Img_processResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROBOT_DEMO_MESSAGE_IMG_PROCESS_H
