// Generated by gencpp from file probot_demo/Img_processRequest.msg
// DO NOT EDIT!


#ifndef PROBOT_DEMO_MESSAGE_IMG_PROCESSREQUEST_H
#define PROBOT_DEMO_MESSAGE_IMG_PROCESSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace probot_demo
{
template <class ContainerAllocator>
struct Img_processRequest_
{
  typedef Img_processRequest_<ContainerAllocator> Type;

  Img_processRequest_()
    : signal()  {
    }
  Img_processRequest_(const ContainerAllocator& _alloc)
    : signal(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _signal_type;
  _signal_type signal;





  typedef boost::shared_ptr< ::probot_demo::Img_processRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_demo::Img_processRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Img_processRequest_

typedef ::probot_demo::Img_processRequest_<std::allocator<void> > Img_processRequest;

typedef boost::shared_ptr< ::probot_demo::Img_processRequest > Img_processRequestPtr;
typedef boost::shared_ptr< ::probot_demo::Img_processRequest const> Img_processRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_demo::Img_processRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_demo::Img_processRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace probot_demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'probot_demo': ['/home/li/ROS/probot_ws/src/PROBOT_Anno/probot_demo/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::probot_demo::Img_processRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_demo::Img_processRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_demo::Img_processRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_demo::Img_processRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_demo::Img_processRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_demo::Img_processRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_demo::Img_processRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e93167e1e15e1e729c30c3dd06f40a8";
  }

  static const char* value(const ::probot_demo::Img_processRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e93167e1e15e1e7ULL;
  static const uint64_t static_value2 = 0x29c30c3dd06f40a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_demo::Img_processRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_demo/Img_processRequest";
  }

  static const char* value(const ::probot_demo::Img_processRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_demo::Img_processRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] signal\n\
\n\
";
  }

  static const char* value(const ::probot_demo::Img_processRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_demo::Img_processRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Img_processRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_demo::Img_processRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_demo::Img_processRequest_<ContainerAllocator>& v)
  {
    s << indent << "signal[]" << std::endl;
    for (size_t i = 0; i < v.signal.size(); ++i)
    {
      s << indent << "  signal[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.signal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_DEMO_MESSAGE_IMG_PROCESSREQUEST_H
